export type IndicatorKey =
  | 'population'
  | 'industry_per_capita'
  | 'food_per_capita'
  | 'pollution_pressure'
  | 'human_welfare'
  | 'industry_total'
  | 'persistent_pollution_stock'
  | 'resources_remaining_pct';

export type Localized = { en: string; ro: string };

export interface IndicatorMeta {
  key: IndicatorKey;
  label: Localized;
  shortLabel: Localized;
  unit: Localized;
  source: Localized;
  sourceUrl: string;
  status: Localized;
  theory: Localized;
  role: Localized;
  interpretationBoundary: Localized;
}

export const indicatorOrder: IndicatorKey[] = [
  'population',
  'industry_per_capita',
  'food_per_capita',
  'pollution_pressure',
  'human_welfare',
  'industry_total',
  'persistent_pollution_stock',
  'resources_remaining_pct',
];

export const dashboardOrder: IndicatorKey[] = [
  'population',
  'food_per_capita',
  'industry_per_capita',
  'pollution_pressure',
  'human_welfare',
];

export const indicators: Record<IndicatorKey, IndicatorMeta> = {
  population: {
    key: 'population',
    label: { en: 'World population', ro: 'Populație mondială' },
    shortLabel: { en: 'Population', ro: 'Populație' },
    unit: { en: 'billion people', ro: 'miliarde persoane' },
    source: { en: 'World Bank — global population', ro: 'World Bank — populație globală' },
    sourceUrl: 'https://api.worldbank.org/v2/country/WLD/indicator/SP.POP.TOTL',
    status: {
      en: 'Observations through 2025; the 2025 value may be an estimate.',
      ro: 'Observații până în 2025; valoarea 2025 poate fi o estimare.',
    },
    theory: {
      en: 'Population is a stock shaped by births and deaths. In World3 those rates respond to food, services, crowding and material living conditions with delays. The empirical layer compares the model trajectory with observed global population without turning the observations into a new feedback loop.',
      ro: 'Populația este un stoc modelat de nașteri și decese. În World3, aceste rate răspund la hrană, servicii, aglomerare și condițiile materiale de trai cu întârzieri. Stratul empiric compară traiectoria modelului cu populația globală observată fără a transforma observațiile într-un feedback nou.',
    },
    role: {
      en: 'Reference stock: four age cohorts with births, deaths and maturation flows.',
      ro: 'Stoc de referință: patru cohorte de vârstă, cu fluxuri de nașteri, decese și maturizare.',
    },
    interpretationBoundary: {
      en: 'Observed population is a comparator and calibration target, not a replacement for the World3 demographic feedback structure.',
      ro: 'Populația observată este reper și țintă de calibrare, nu înlocuiește structura feedbackurilor demografice World3.',
    },
  },
  industry_per_capita: {
    key: 'industry_per_capita',
    label: { en: 'Industrial output per capita', ro: 'Producție industrială pe locuitor' },
    shortLabel: { en: 'Industry / capita', ro: 'Industrie / locuitor' },
    unit: { en: 'index, 2015=100', ro: 'indice, 2015=100' },
    source: { en: 'World Bank — industry / population', ro: 'World Bank — industrie / populație' },
    sourceUrl: 'https://api.worldbank.org/v2/country/WLD/indicator/NV.IND.TOTL.KD',
    status: {
      en: 'Observations start in 1992; industry includes construction. The chart is per capita, not total output.',
      ro: 'Observațiile încep în 1992; industria include construcțiile. Graficul este per capita, nu producție totală.',
    },
    theory: {
      en: 'Industrial output per capita links the industrial-capital stock to population. It is central to material consumption and to the investment available for services, agriculture and resource extraction. The empirical series begins later than population and includes construction.',
      ro: 'Producția industrială pe locuitor leagă stocul de capital industrial de populație. Este centrală pentru consumul material și pentru investițiile disponibile în servicii, agricultură și extracția resurselor. Seria empirică începe mai târziu decât populația și include construcțiile.',
    },
    role: {
      en: 'Auxiliary generated by industrial capital, capacity utilisation and population.',
      ro: 'Auxiliar derivat din capitalul industrial, utilizarea capacității și populație.',
    },
    interpretationBoundary: {
      en: 'The World Bank series is an empirical proxy. UNIDO diagnostics remain independent evidence and do not automatically replace this bridge.',
      ro: 'Seria World Bank este un proxy empiric. Diagnosticele UNIDO rămân dovezi independente și nu înlocuiesc automat această punte.',
    },
  },
  food_per_capita: {
    key: 'food_per_capita',
    label: { en: 'Food production per capita', ro: 'Producție alimentară pe locuitor' },
    shortLabel: { en: 'Food / capita', ro: 'Hrană / locuitor' },
    unit: { en: 'FAO index, 2014–2016=100', ro: 'indice FAO, 2014–2016=100' },
    source: { en: 'FAOSTAT — Food, gross per capita', ro: 'FAOSTAT — Food, gross per capita' },
    sourceUrl: 'https://www.fao.org/faostat/en/#data/QI',
    status: {
      en: 'FAOSTAT observations through 2024. The observation bridge combines 25% of the World3 food signal and 75% of industrial input capacity; it does not add a new agricultural feedback.',
      ro: 'Observații FAOSTAT până în 2024. Puntea de observație combină 25% semnalul alimentar World3 și 75% capacitatea industrială de input; nu adaugă un feedback agricol nou.',
    },
    theory: {
      en: 'Food per capita emerges from agricultural capital, land, inputs and pollution/resource constraints. In BAU Hybrid 2026 the displayed empirical bridge improves comparability with FAOSTAT but is not a newly estimated agricultural feedback.',
      ro: 'Hrana pe locuitor rezultă din capitalul agricol, teren, inputuri și constrângerile de resurse/poluare. În BAU Hibrid 2026, puntea empirică afișată îmbunătățește comparabilitatea cu FAOSTAT, dar nu este un feedback agricol nou estimat.',
    },
    role: {
      en: 'Auxiliary produced by the agriculture subsystem from land, fertility, agricultural capital and inputs.',
      ro: 'Auxiliar produs de subsistemul agricol din teren, fertilitate, capital agricol și inputuri.',
    },
    interpretationBoundary: {
      en: 'The empirical bridge is a measurement bridge only. Climate–food candidates that failed prospective gates remain outside the central feedback structure.',
      ro: 'Puntea empirică este doar o punte de măsurare. Candidații climă–hrană care nu au trecut porțile prospective rămân în afara structurii centrale de feedback.',
    },
  },
  pollution_pressure: {
    key: 'pollution_pressure',
    label: { en: 'Annual CO₂ emissions (activity proxy)', ro: 'Emisii CO₂ anuale (proxy activitate)' },
    shortLabel: { en: 'CO₂ activity', ro: 'Activitate CO₂' },
    unit: { en: 'flow index, 1990=100', ro: 'indice de flux, 1990=100' },
    source: { en: 'World Bank / EDGAR — CO₂ proxy', ro: 'World Bank / EDGAR — proxy CO₂' },
    sourceUrl: 'https://edgar.jrc.ec.europa.eu/dataset_ghg2025',
    status: {
      en: 'Observations through 2024. Annual CO₂ is represented by industrial activity; generation and the persistent-pollution stock remain separate latent World3 mechanisms.',
      ro: 'Observații până în 2024. CO₂ anual este reprezentat prin activitatea industrială; generarea și stocul de poluare persistentă rămân mecanisme latente World3 separate.',
    },
    theory: {
      en: 'The original World3 persistent-pollution mechanism is a stock with generation and assimilation delays. The observed annual CO₂ series is only an activity proxy for comparison; it is not treated as the persistent stock itself.',
      ro: 'Mecanismul original World3 al poluării persistente este un stoc cu întârzieri de generare și asimilare. Seria observată de CO₂ anual este doar un proxy de activitate pentru comparație; nu este tratată ca stocul persistent însuși.',
    },
    role: {
      en: 'Observed flow proxy kept distinct from the World3 persistent-pollution stock and its generation/assimilation flows.',
      ro: 'Proxy de flux observat, menținut distinct de stocul World3 de poluare persistentă și fluxurile sale de generare/asimilare.',
    },
    interpretationBoundary: {
      en: 'Energy/emissions accounting is an inactive candidate interface. It has not been promoted into a central feedback.',
      ro: 'Contabilitatea energie/emisii este o interfață candidat inactivă. Nu a fost promovată într-un feedback central.',
    },
  },
  human_welfare: {
    key: 'human_welfare',
    label: { en: 'Human development', ro: 'Dezvoltare umană' },
    shortLabel: { en: 'Human development', ro: 'Dezvoltare umană' },
    unit: { en: 'index 0–1', ro: 'indice 0–1' },
    source: { en: 'UNDP — Human Development Index', ro: 'UNDP — Human Development Index' },
    sourceUrl: 'https://hdr.undp.org/data-center/documentation-and-downloads',
    status: {
      en: 'Observations through 2023; HDI is not identical to the World3 HWI.',
      ro: 'Observații până în 2023; HDI nu este identic cu HWI din World3.',
    },
    theory: {
      en: 'Human development is used as an empirical welfare comparator. It does not equal the original World3 human-welfare index, so the match is interpreted as a diagnostic rather than a literal identity of constructs.',
      ro: 'Dezvoltarea umană este folosită ca reper empiric de bunăstare. Nu este identică cu indicele de bunăstare umană World3, deci potrivirea este interpretată diagnostic, nu ca identitate literală a constructelor.',
    },
    role: {
      en: 'Empirical welfare comparator against a derived World3 welfare construct.',
      ro: 'Comparator empiric de bunăstare față de un construct de bunăstare derivat din World3.',
    },
    interpretationBoundary: {
      en: 'HDI and the World3 human-welfare index are related but non-identical constructs; agreement is descriptive, not construct identity.',
      ro: 'HDI și indicele World3 de bunăstare umană sunt constructe înrudite, dar neidentice; concordanța este descriptivă, nu identitate de construct.',
    },
  },
  industry_total: {
    key: 'industry_total',
    label: { en: 'Total industrial output', ro: 'Producție industrială totală' },
    shortLabel: { en: 'Total industry', ro: 'Industrie totală' },
    unit: { en: 'index, 2015=100', ro: 'indice, 2015=100' },
    source: { en: 'World Bank — total industrial output', ro: 'World Bank — producție industrială totală' },
    sourceUrl: 'https://api.worldbank.org/v2/country/WLD/indicator/NV.IND.TOTL.KD',
    status: {
      en: 'Observed diagnostic anchored exactly in 2025. It is not weighted a second time in calibration because it is derived from population and output per capita.',
      ro: 'Diagnostic observat și ancorat exact în 2025. Nu intră separat în calibrare, fiind derivat din populație și producția pe locuitor.',
    },
    theory: {
      en: 'Total industrial output is derived from population and industrial output per capita. It is displayed as a coherence diagnostic and is deliberately not given a second independent calibration weight.',
      ro: 'Producția industrială totală este derivată din populație și producția industrială pe locuitor. Este afișată ca diagnostic de coerență și nu primește deliberat o a doua pondere independentă în calibrare.',
    },
    role: { en: 'Derived observed diagnostic.', ro: 'Diagnostic observat derivat.' },
    interpretationBoundary: {
      en: 'Because it is derived from population and per-capita output, it is not an independent calibration target.',
      ro: 'Fiind derivat din populație și producția per capita, nu este o țintă independentă de calibrare.',
    },
  },
  persistent_pollution_stock: {
    key: 'persistent_pollution_stock',
    label: { en: 'Persistent pollution stock (latent)', ro: 'Stoc de poluare persistentă (latent)' },
    shortLabel: { en: 'Pollution stock', ro: 'Stoc poluare' },
    unit: { en: 'World3 index, 1990=100', ro: 'indice World3, 1990=100' },
    source: { en: 'World3-03 — modelled persistent stock', ro: 'World3-03 — stoc persistent modelat' },
    sourceUrl: 'https://web.mit.edu/jsterman/www/DID.html',
    status: {
      en: 'Latent World3 state with no directly equivalent global observation. It represents persistent-pollution accumulation minus assimilation.',
      ro: 'Stare latentă World3, fără observație globală direct echivalentă. Arată acumularea minus asimilarea poluării persistente.',
    },
    theory: {
      en: 'Persistent pollution is a latent stock in the World3 structure. It integrates pollution generation and delayed assimilation; there is no single observed global series that is treated as an exact measurement of this stock.',
      ro: 'Poluarea persistentă este un stoc latent în structura World3. Integrează generarea poluării și asimilarea întârziată; nu există o singură serie globală observată tratată drept măsurare exactă a acestui stoc.',
    },
    role: { en: 'Reference stock with generation and assimilation flows.', ro: 'Stoc de referință cu fluxuri de generare și asimilare.' },
    interpretationBoundary: {
      en: 'No observed series is fabricated for this latent state. Annual CO₂ remains a separate activity proxy.',
      ro: 'Nu este fabricată nicio serie observată pentru această stare latentă. CO₂ anual rămâne un proxy separat de activitate.',
    },
  },
  resources_remaining_pct: {
    key: 'resources_remaining_pct',
    label: { en: 'Non-renewable resources remaining (latent)', ro: 'Resurse neregenerabile rămase (latent)' },
    shortLabel: { en: 'Resources remaining', ro: 'Resurse rămase' },
    unit: { en: 'stock index, BAU 1900=100', ro: 'indice de stoc, BAU 1900=100' },
    source: { en: 'World3-03 — modelled non-renewable resources', ro: 'World3-03 — resurse neregenerabile modelate' },
    sourceUrl: 'https://web.mit.edu/jsterman/www/DID.html',
    status: {
      en: 'Latent World3 state with no direct observation. All curves use the same denominator: BAU stock in 1900 = 100; BAU2 therefore starts at 200.',
      ro: 'Stare latentă World3, fără observație directă. Toate curbele folosesc același numitor: stocul BAU din 1900 = 100; de aceea BAU2 pornește de la 200.',
    },
    theory: {
      en: 'Non-renewable resources are a latent depletion stock. The chart preserves the original World3 accounting convention and makes the different initial BAU/BAU2 resource assumptions visible rather than renormalising them away.',
      ro: 'Resursele neregenerabile sunt un stoc latent de epuizare. Graficul păstrează convenția contabilă World3 originală și face vizibile ipotezele inițiale diferite BAU/BAU2, fără a le renormaliza.',
    },
    role: { en: 'Reference depletion stock with a resource-usage outflow.', ro: 'Stoc de referință de epuizare cu flux de consum al resurselor.' },
    interpretationBoundary: {
      en: 'Observed mining flows and reserves are not treated as direct measurements of the latent World3 stock, and resource fraction → fossil EROI coupling remains forbidden.',
      ro: 'Fluxurile miniere și rezervele observate nu sunt tratate ca măsurători directe ale stocului latent World3, iar cuplarea fracțiune resurse → EROI fosil rămâne interzisă.',
    },
  },
};
